### ISSUE TITLE
Rate limit enforced for cache purge

### ISSUE THREAD

**Issue by JacobDorman** [danielpigott/cloudflare-cli#15]
I'm getting this a lot, even when I haven't used cfcli in days or weeks.

Other times it works without issue.

**Comment by danielpigott** [comment]
This message is coming directly from the cloudflare api, so there isn't really anything that can be done in cfcli to change it  The rate limit will include any other cache clears you have performed via the web interface or api so that might be why you are getting the message without having called purgecache via cfcli
